### ISSUE TITLE
Set SocketInteraction.GuildId public

### ISSUE THREAD

**Issue by sizumita** [Discord-Net-Labs/Discord.Net-Labs#202]
https://github.com/Discord-Net-Labs/Discord.Net-Labs/blob/a4c024aa13fd042d45520d1f54fd3563b77e04e5/src/Discord.Net.WebSocket/Entities/Interaction/SocketInteraction.cs#L56
I want to get guild id from SocketInteraction(in SocketSlashCommand), but GuildId is private.
Are there any reasons?

**Comment by quinchs** [comment]
The interaction could be triggered outside of a guild, the way you can get and check the guild id is to check the type of the channel, for example
```cs
ulong? guildId = (interaction.Channel as IGuildChannel)?.GuildId;
```

**Comment by GreemDev** [comment]
Why should we need to do a channel cast to get a nullable value that's already present *on the object*?

**Comment by quinchs** [comment]
Tbh that property should be deprecated and removed as its basically useless. The casting standard is used alot within the library and its just how the library works ig.

**Comment by quinchs** [comment]
Removed in [78879da](https://github.com/Discord-Net-Labs/Discord.Net-Labs/commit/78879da5c1cf6a1a80bfb5de52826bfa32d45a20)

**Comment by GreemDev** [comment]
So instead of making a private property public the property was removed because "that's just how the library works I guess."

Why not, instead, improve the library. Instead of forcing users to cast repeatedly or store the value itself, why not let us access the value that was already present on the `SocketInteraction` type, and that is *provided by Discord*.

**Comment by quinchs** [comment]
The entities are designed to contain their **set** values and related entities. If a property is optional it isnt normally included unless necessary.

You can access the guild Id and a whole guild object by checking the channel type if you need. This is standard with the library.

Exposing optional or nullable fields are often not good because it leads to confusion and overhead with code. Sure you might find it helpful and intuitive to you but others may not. I'm sorry that the standard that over 40k people have adapted to isnt up to your likening.

**Comment by quinchs** [comment]
If you want another example of how this is used in the library take a look at `SocketUserMessage` or any message in that case. [Message objects](https://discord.com/developers/docs/resources/channel#message-object) contain a nullable guild id in them but there is no exposed or even private field for it in any socket or rest based messages.
