### ISSUE TITLE
Clients using SetActivityAsync get disconnected and reconnected

### ISSUE THREAD

**Issue by quinchs** [Discord-Net-Labs/Discord.Net-Labs#83]
# Summary
Sharded clients seem to behave oddly when using the 3.X branch, the root cause of the behavior is still unknown and further testing is required.

![image](https://user-images.githubusercontent.com/49576606/128317479-f6b7e288-1726-42a5-ac7d-6fbdbe45fe0a.png)
![image](https://user-images.githubusercontent.com/49576606/128317520-345ba5d8-dcba-41c2-9a1b-eca23120fa6b.png)

Im unable to reproduce locally so if anyone has any debug information that they can supply please do

**Comment by MrCakeSlayer** [comment]
Additional notes:
- Adjusting ConnectionTimeout seems to have zero affect
- Occurs both if you specify specific shard numbers and if you don't specify the specific shard numbers
- Happens when there are at least 4 shards (Might occur when fewer shards are set?)
- Does not throw exception errors
- Fires the Shard Ready events as expected
- Shards disconnect with the "WebSocket connection was closed" then 'fails to resume'

Config:
```cs
services.AddSingleton(new DiscordShardedClient(new[] {0, 1, 2, 3}, new DiscordSocketConfig()
{
	LogLevel = LogSeverity.Verbose,
	MessageCacheSize = Config.Instance.Bot.MessageCache,
	TotalShards = Config.Instance.Bot.DebugMode ? 1 : Config.Instance.Bot.Shards,
	DefaultRetryMode = RetryMode.AlwaysFail,
	AlwaysDownloadUsers = false,
	AlwaysAcknowledgeInteractions = false,
	GatewayIntents = intents
}));
```

**Comment by MrCakeSlayer** [comment]
Appears to be an issue with `SetStatusAsync()` and `SetGameAsync()`
(Also affects SocketClients, not just ShardedClients)

**Comment by quinchs** [comment]
```
Disconnected
Failed to start the connection: System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4001: "Unknown opcode."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken) in C:\Users\lynch\Documents\GitHub\Discord.Net Labs\Discord.Net-Labs\src\Discord.Net.WebSocket\Net\DefaultWebSocketClient.cs:line 216
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\lynch\Documents\GitHub\Discord.Net Labs\Discord.Net-Labs\src\Discord.Net.WebSocket\ConnectionManager.cs:line 76
Failed to start the connection: System.Exception: WebSocket connection was closed
 ---> Discord.Net.WebSocketClosedException: The server sent close 4001: "Unknown opcode."
   at Discord.Net.WebSockets.DefaultWebSocketClient.RunAsync(CancellationToken cancelToken) in C:\Users\lynch\Documents\GitHub\Discord.Net Labs\Discord.Net-Labs\src\Discord.Net.WebSocket\Net\DefaultWebSocketClient.cs:line 216
   --- End of inner exception stack trace ---
   at Discord.ConnectionManager.<>c__DisplayClass29_0.<<StartAsync>b__0>d.MoveNext() in C:\Users\lynch\Documents\GitHub\Discord.Net Labs\Discord.Net-Labs\src\Discord.Net.WebSocket\ConnectionManager.cs:line 76
Connecting
Connecting ApiClient
```

**Comment by quinchs** [comment]
Please pull and let me know if the issue persists

**Comment by quinchs** [comment]
When using `SetActivityAsync`, the client will connect, hang for 2 seconds, and reconnect with no issue. It seems like the presence is getting sent multiple times

**Comment by Misha12** [comment]
@quinchs 
I downloaded Discord.Net.Labs 3.2.0 from NuGet and the problem still occurs. When i call SetStatusAsync before Ready event so everything is done correctly. When i call same method after Ready so it will cause reconnect with InvalidSession. Of course, calling the method in Ready event will cause infinite loop.

Call before Ready event (there will be no problem):
```
await DiscordSocketClient.LoginAsync(TokenType.Bot, token);
await DiscordSocketClient.StartAsync();
await DiscordSocketClient.SetStatusAsync(UserStatus.Idle);
```

Log from call SetStatusAsync inside Ready event (I highlighted the places where the Ready event ends.):
![image](https://user-images.githubusercontent.com/9041462/142259262-285baddf-c51b-42c5-91ac-601edf2a6a02.png)

If necessary, ask, but I have no idea if I can provide any more information. Of course, I can rewrite the application so that it does not use the Status property, but I think this is a library bug and the problem should be resolved on the library side.
